sonar.projectKey=ghisl_Hello
sonar.organization=ghisl
sonar.projectName=Hello DevOps Project
sonar.projectVersion=1.0.0

sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.java.coverage.reportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=**/config/**,**/entity/**,**/dto/**,**/Application.class
sonar.coverage.exclusions=**/config/**,**/entity/**,**/dto/**,**/Application.class
